### PR TITLE
Hets 114

### PR DESCRIPTION
**Pull request by GeorgeWalker**

### CODE REVIEW

**Comment by robinwn** [comment]
@GeorgeWalker - would you please review the conflicts

**Comment by GeorgeWalker** [comment]
This one is ready to integrate Robin.

**Comment by robinwn** [comment]
@GeorgeWalker - conflicts have reappeared - has this series of PRs had order dependant changes?

**Comment by GeorgeWalker** [comment]
It should be OK to merge now

**Pull request merged**
