### PR TITLE
HETS-83 Add attributes to meet DA Standards to the swagger definition…

### PR DESCRIPTION
**Pull request by swcurran**
…s - data model

### CODE REVIEW

**Comment by robinwn** [comment]
@swcurran - is  APISpec/HETSswagger.yaml.bk just a backup file?

**Comment by swcurran** [comment]
It is the previous version, which is useful for diffing with the version
being submitted.  But yes, we could gitignore it. We do that in School Bus.

**Comment by robinwn** [comment]
Let's go with the .gitignore - thx

**Comment by swcurran** [comment]
Good to go.

**Pull request merged**
